# GitHub Actions workflow for automated npm publishing
# Uses Changesets for versioning + npm Trusted Publishers (OIDC) for secure publishing
#
# Key features:
# - No NPM_TOKEN secret needed (uses OIDC authentication)
# - Automatic version bumping via Changesets
# - Creates "chore: release packages" PR when changesets exist
# - Auto-publishes when that PR is merged
# - Supports monorepos with selective package publishing

name: Release

on:
  push:
    branches: [main]

# Prevent concurrent releases
concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: write        # Required for Changesets to commit version bumps
  pull-requests: write   # Required for Changesets to create release PRs
  id-token: write        # Required for npm OIDC authentication (Trusted Publishers)

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full git history needed for Changesets

      # Install package managers
      - uses: oven-sh/setup-bun@v2
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org"

      # Install dependencies
      - run: bun install

      # Build all packages EXCEPT docs/website (not published to npm)
      # Adjust filter pattern to match your monorepo structure
      - run: bun turbo build --filter='!@org/docs' --filter='!@org/web'

      # Configure npm authentication
      # For OIDC (Trusted Publishers): NPM_TOKEN is auto-generated by npm CLI 11.5.1+
      # For classic tokens: Use secrets.NPM_TOKEN
      - name: Setup npmrc
        run: |
          echo "//registry.npmjs.org/:_authToken=\${{ secrets.NPM_TOKEN }}" > .npmrc
        # Note: If using OIDC, NPM_TOKEN can be empty - npm CLI auto-detects CI environment

      # Changesets action handles two flows:
      # 1. If changesets exist → create/update "chore: release packages" PR with version bumps
      # 2. If on main + versions bumped → publish to npm
      - uses: changesets/action@v1
        with:
          # Custom scripts defined in root package.json:
          # ci:version - runs "changeset version" + optional post-processing
          # ci:publish - runs custom publish script (handles workspace:* resolution)
          version: bun run ci:version
          publish: bun run ci:publish
          title: "chore: release packages"
          commit: "chore: release packages"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}  # Leave empty if using OIDC

# Usage:
# 1. Configure npm Trusted Publisher (see SKILL.md)
# 2. Add this workflow to .github/workflows/publish.yml
# 3. Create changesets: bunx changeset (or manually create .changeset/*.md)
# 4. Push to main → Changesets creates version bump PR
# 5. Merge PR → Auto-publishes to npm
#
# Troubleshooting:
# - "Could not resolve workspaces" → Add packageManager field to root package.json
# - "workspace:* not resolved" → Use custom publish script (see publish-script.ts)
# - "OIDC auth failed" → Verify Trusted Publisher config matches workflow path
